name: GoldSilver Hourly

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci || npm i

      - name: Run bot
        env:
          BOT: ${{ secrets.BOT }}
          CHAT: ${{ secrets.CHAT }}
        run: node index.js

      - name: Commit state if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add state.json || true
            git commit -m "chore: update signal state [skip ci]" || true
            git push
          fi
